### PR TITLE
Add support for scopedVars

### PR DESCRIPTION
**Pull request by brynjare**
I've given some thought to #13, and ended up passing options.scopedVars along to all the interpolate*()-functions.

In any case, this code should add support for scopedVars for attributes, expressions and filters alike. Here's a demonstration of the new feature for all three query types, with row-based repeats for $minions, and panel-based repeats for $subAttribute:

fixedscopedvars

### CODE REVIEW

**Comment by roskens** [comment]
Should there be additional scoped variables unit tests?

**Comment by brynjare** [comment]
I have to admit I haven't looked into them at all until just now, so I don't know much about them at the moment. Since they also use template variables, it's probably necessary to extend the tests as well.

I'm not sure when I'll have time to familiarise myself with the unit tests and extend them with support for scoped vars, but I'll look into it as soon as I get an opportunity. Thanks for pointing them out to me!

**Comment by mforgues** [comment]
brynjare, do you recall which version of grafana your branch used to work with? 

I have tried reapplying the same steps as in the video but I can't get one graph per node per subattribute. I only get the same graph repeated times the number of subattributes and times the number of selected nodes.

**Comment by brynjare** [comment]
@mforgues I've only committed the source file, so perhaps you're still using the original (untouched) files under the 'dist/'-folder? To test the changes in my pull request, you'll need to [deploy the updated sources](https://github.com/OpenNMS/grafana-opennms-datasource/blob/master/HACKING.md).

Please let me know if you've already done that, and it still doesn't take effect.

**Comment by j-white** [comment]
This commit was adapted to the performance data source in the `opennms-helm` project: https://github.com/OpenNMS/opennms-helm/commit/4abbdea6d0d5a6a78c30bfb8a6bfa7dcce7c3ad4#diff-f868fa8ce07626c4a5237ab175298dec.

**Pull request closed without merging**
